import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Understand Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href={'/csr'}>CSR</Link>
        <Link href={'/ssr'}>SSR</Link>
        <Link href={'/ssg'}>SSG</Link>
      </main>
    </>
  )
}
