import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { GetServerSideProps } from 'next'



export default function Home({title}:any)  {
  return (
    <>
      <Head>
        <title>Server Side Rendering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          {title !== ''? `CSR (Server Side Rendering) - ${title}` : <p>SSR (Server Side Rendering) - Loading...</p>}
        </h1> 
      </main>
    </>
  )
}

export const getServerSideProps:GetServerSideProps = async () => {
  const res = await axios.get('https://dummyjson.com/products/1').then(res => res)
  const data = await res.data
  return {
    props: data
  }
}
