import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'


export default function Home() {
  const [fetchMessage, setFetchMessage] = useState<string>('')
  useEffect(() => {
      axios
      .get('https://dummyjson.com/products/1')
      .then((res) => {
        setFetchMessage(res.data.title);
      })
      .catch((error) => console.error(error));
    }, [])
  return (
    <>
      <Head>
        <title>Client-Side Rendering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          {fetchMessage !== ''? `CSR (Client Side Rendering) - ${fetchMessage}` : <p>CSR (Client Side Rendering) - Loading...</p>}
        </h1> 
      </main>
    </>
  )
}
